image: registry.backpackcloud.com/backpackcloud/maven

workflow:
  rules:
    - if: $CI_COMMIT_TAG
      when: never
    - when: always

stages:
  - release

downstream:publish:
  stage: release
  script:
    - release downstream
