image: registry.backpackcloud.com/backpackcloud/maven

stages:
  - downstream
  - upstream

downstream:publish:
  stage: downstream
  script:
    - release downstream

upstream:publish:
  stage: upstream
  script:
    - release upstream
